import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class TransactionRecord {
  final String id;
  final String merchant;
  final double amount;
  final String currency;
  final DateTime date;
  final String category;

  const TransactionRecord({
    required this.id,
    required this.merchant,
    required this.amount,
    required this.currency,
    required this.date,
    required this.category,
  });
}

class PdfService {
  static final PdfService _instance = PdfService._internal();
  factory PdfService() => _instance;
  PdfService._internal();

  static PdfService get instance => _instance;

  Future<String> generateMonthlyReport({
    required int year,
    required int month,
    required List<TransactionRecord> transactions,
  }) async {
    final pdf = pw.Document();
    final monthName = DateFormat('MMMM yyyy').format(DateTime(year, month));
    final total = transactions.fold<double>(0, (s, t) => s + t.amount);
    final categories = <String, double>{};
    for (final t in transactions) {
      categories[t.category] = (categories[t.category] ?? 0) + t.amount;
    }
    final sortedCategories = categories.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              'NeoPay AI - Monthly Report',
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(monthName, style: const pw.TextStyle(fontSize: 16)),
          pw.Divider(),
          pw.SizedBox(height: 16),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Total Spending:', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.Text('IDR ${NumberFormat('#,##0.00').format(total)}',
                  style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            ],
          ),
          pw.SizedBox(height: 4),
          pw.Text('Transactions: ${transactions.length}'),
          pw.SizedBox(height: 24),
          pw.Text('By Category', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Table.fromTextArray(
            headers: ['Category', 'Amount', '%'],
            data: sortedCategories.map((e) {
              final pct = total > 0 ? (e.value / total * 100).toStringAsFixed(1) : '0.0';
              return [
                e.key,
                'IDR ${NumberFormat('#,##0.00').format(e.value)}',
                '$pct%',
              ];
            }).toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey800),
            rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
            cellAlignment: pw.Alignment.centerLeft,
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerRight,
              2: pw.Alignment.centerRight,
            },
          ),
          pw.SizedBox(height: 24),
          pw.Text('Transaction Details', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.Table.fromTextArray(
            headers: ['Date', 'Merchant', 'Category', 'Amount'],
            data: transactions.map((t) => [
              DateFormat('dd/MM/yyyy').format(t.date),
              t.merchant,
              t.category,
              'IDR ${NumberFormat('#,##0.00').format(t.amount)}',
            ]).toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey800),
            rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
            cellAlignment: pw.Alignment.centerLeft,
            cellAlignments: {
              0: pw.Alignment.centerLeft,
              1: pw.Alignment.centerLeft,
              2: pw.Alignment.centerLeft,
              3: pw.Alignment.centerRight,
            },
          ),
        ],
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 12),
          child: pw.Text('Generated by NeoPay AI on ${DateFormat('dd/MM/yyyy HH:mm').format(DateTime.now())}',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final fileName = 'neopay_report_${year}_${month.toString().padLeft(2, '0')}.pdf';
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());
    return file.path;
  }

  Future<void> shareReport(String filePath) async {
    await Share.shareXFiles([XFile(filePath)], text: 'My NeoPay AI Monthly Report');
  }
}
