// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0IQF_-z9oF2RaNnKpJJdYyqp8epBHk4M',
    appId: '1:252073680114:web:e2afd231d33bda6e91446b',
    messagingSenderId: '252073680114',
    projectId: 'neopay-42b9a',
    authDomain: 'neopay-42b9a.firebaseapp.com',
    storageBucket: 'neopay-42b9a.firebasestorage.app',
    measurementId: 'G-KTYCM2M1CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRV6C3aFOqwU_odJUIplazn8jrX8XIuI',
    appId: '1:252073680114:android:81a87a6ab720525791446b',
    messagingSenderId: '252073680114',
    projectId: 'neopay-42b9a',
    storageBucket: 'neopay-42b9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbO50rB4akcG50lXF5ZYRcV5y_ttdw5GE',
    appId: '1:252073680114:ios:3d7af19a592d7df191446b',
    messagingSenderId: '252073680114',
    projectId: 'neopay-42b9a',
    storageBucket: 'neopay-42b9a.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbO50rB4akcG50lXF5ZYRcV5y_ttdw5GE',
    appId: '1:252073680114:ios:3d7af19a592d7df191446b',
    messagingSenderId: '252073680114',
    projectId: 'neopay-42b9a',
    storageBucket: 'neopay-42b9a.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0IQF_-z9oF2RaNnKpJJdYyqp8epBHk4M',
    appId: '1:252073680114:web:c39ee385232b09d391446b',
    messagingSenderId: '252073680114',
    projectId: 'neopay-42b9a',
    authDomain: 'neopay-42b9a.firebaseapp.com',
    storageBucket: 'neopay-42b9a.firebasestorage.app',
    measurementId: 'G-Q6SX8ZQCDY',
  );
}
